### PR TITLE
lineprotocol: fix inappropriate skipping after error

### LINKED ISSUE #43: an invalid line causes the next line to be skipped
When parsing multiple lines of line protocol, if a line has a syntax error, the line immediately following it will be skipped. 

For example:
```
foo value=12.0
foo value=2a.0
foo value=32.0
foo value=42.0
```
This will successfully parse the first line, the second line will emit an error, but the third line will be skipped altogether, and finally, the fourth line will also be successfully parsed.

If you add two invalid lines back-to-back, an error will only be reported for the first invalid line. Example:
```
foo value=12.0
foo value=2a.0
foo value=8a.0
foo value=32.0
foo value=42.0
```

Here is the code I was using to test: https://gist.github.com/akrantz01/f047e400a586a7dfaf6006ca2876b7eb.

### PR DESCRIPTION
**Pull request by rogpeppe**
The `syntaxError` logic was skipping to the end of the line,
but that doesn't work when we're already at the end of a line,
so avoid that.

Fixes #43.

### CODE REVIEW

File: lineprotocol/decoder_test.go [hunk 1]
```diff
@@ -474,10 +532,10 @@ func TestDecoderSkipSection(t *testing.T) {
 						if i >= len(test.expect) {
 							continue
 						}
-						if e := expectedSectionError(test.expect[i], sect-1); e != "" && !strings.Contains(e, "out of range") {
+						if e := expectedSectionError(test.expect[i], sect-1); e != "" && !strings.Contains(e, "cannot parse value for field key") {
 							// If there's an error earlier in the line, it gets returned on the
-							// later section (unless it's an out of range error, in which case it's technically valid
-							// syntax)
+							// later section (unless it's an error parsing a field value, in which case
+							// it the syntax checking is more lax).
```
Comment (andrewcharlton) [inline lineprotocol/decoder_test.go:538]: > in which case it the syntax check is more lax

?

File: lineprotocol/decoder_test.go [hunk 2]
```diff
@@ -206,6 +206,64 @@ var decoderTests = []struct {
 		}},
 		Time: "1602841605822792000",
 	}},
+}, {
+	testName: "multiple-entries-with-error#1",
+	text: `
+m1§ §value=12.0§
+¶m2§ §value=∑¹2a.0§
```
Comment (andrewcharlton) [inline lineprotocol/decoder_test.go:213]: I think I've asked this before, but what's the point of the `¶§∑¹` symbols in here?  Why is it not just standard line protocol input?

File: lineprotocol/decoder_test.go (hunk 1 above)
Comment (rogpeppe) [reply lineprotocol/decoder_test.go:538]: fixed.

File: lineprotocol/decoder_test.go (hunk 2 above)
Comment (rogpeppe) [reply lineprotocol/decoder_test.go]: It's documented in the doc comment for the `text` field: § and ¶ function as metacharacters that allow us to use the same input text for a variety of tests...

But, having just reviewed this, they were actually only used for the now-removed `NewDecoderAtSection` tests, so they can be removed themselves. Done.

The ∑ symbols are to save hard-coding the error position offsets into the error strings. They were essential with `NewDecoderAtSection` because the error position was different in different tests, but they're still useful for readability and maintainability now, I think, so I've left them in.

File: lineprotocol/decoder_test.go [hunk 3]
```diff
@@ -494,8 +550,8 @@ func TestDecoderSkipSection(t *testing.T) {
 func removeTestSeparators(s string) string {
```
Comment (andrewcharlton) [inline lineprotocol/decoder_test.go:550]: does this just need to be removed entirely now?

Comment (rogpeppe) [reply lineprotocol/decoder_test.go]: yup! good call, done.

**Review by andrewcharlton — APPROVED** [review]
